name: Development pipeline

on:
  push:
    branches:
      - mahesh-dev

jobs:
  deploy:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          npm-version: '10'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build npm
        run: npm run build
